server:
  port: 8090
  servlet:
    context-path: /

#redis
redis:
  host: @redis.host@
  port: @redis.port@
  timeout: 10
  poolMaxTotal: 1000
  poolMaxIdle: 500
  poolMaxWait: 500
  password: @redis.password@

spring:
  datasource:
    schema: classpath:db/schema.sql
    data: classpath:db/data.sql
    schema-username: root
    schema-password: zhanghang
    initialization-mode: always
    url: jdbc:mysql://127.0.0.1:3306/data?characterEncoding=UTF-8&serverTimezone=GMT
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: zhanghang
    dbcp2:
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      validation-query: select 'x'
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
  kafka:
    bootstrap-servers: @kafka.bootstrap@
    template:
      default-topic: config-default-topic
    producer:
      retries: 0
      #每次批量发送的消息数量
      batch-size: 16384
      buffer-memory: 33554432
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        linger.ms: 1

#mybatis
mybatis:
  mapperLocations: classpath:mapper/*.xml
  typeAliasesPackage: com.hang.server.entity.po
  config-location: classpath:mybatis-config.xml

logging:
  config: classpath:logback.xml